apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component--bygu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component--bygu
    app.kubernetes.io/part-of: test-app-kdyj
  name: test-component--bygu
  namespace: e2e-test-pipelines-ydep
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component--bygu
status:
  loadBalancer: {}
